PREFIX              = "demo"
RG_LOCATION         = "northeurope"
VNET_ADDRESS        = "10.0.0.0/16"
VNET_SUBNET_ADDRESS = "10.0.0.0/24"
USERNAME            = "linuxusr"
STORAGE_ACCOUNT     = "bootdiagonistic"